apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-poc.fullname" . }}
  labels:
    {{- include "vault-poc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vault-poc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault-poc.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ printf "%s-sa" .Values.application.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
        {{- range .Values.objects }}
        - name: {{ printf "%s-volume" .objectName }}
          mountPath: "/mnt/{{ .secretPath }}"
          readOnly: true
        {{- end }}
        env:
        {{- range .Values.objects }}
        - name: {{ printf "%s" .objectName | upper | replace "-" "_" }}
          valueFrom:
            secretKeyRef:
              name: {{ .objectName }}
              key: {{ .objectName }}
        {{- end }}
      volumes:
      {{- $appName := .Values.application.name }}
      {{- range .Values.objects }}
      - name: {{ printf "%s-volume" .objectName }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ printf "%s-spc" $appName }}
      {{- end }}