# A SecretProviderClass that uses secret syncing to create Secret objects from Vault secrets.
# See https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
spec:
  provider: vault
  secretObjects:
{{- range .Values.secrets }}
    - secretName: {{ .name }}
      type: Opaque
      data:
      - key: {{ .key }}
        objectName: {{ .objectName }}
{{- end }}
  parameters:
    vaultAddress: "http://vault.default.svc:8200"
    roleName: {{ .Values.secretProviderClass.roleName | quote }}
    objects: |
{{ toYaml .Values.secretProviderClass.objects | indent 6 }}
